config/routes.rb
Rails.application.routes.draw do
  scope constraints: lambda { |r| !sub_domain?(r) }, via: :all do
    root 'static#index'
    match '/gateway_auth/:provider', to: lambda{ |env| [404, {}, ['Not Found']] }, as: 'auth'
    get '/gateway_auth/slack/callback' => 'session#slack_callback'

    resources :proxy_rules
  end

  scope constraints: lambda { |r| sub_domain?(r) }, via: :all do
    get '/' => 'proxy_rules#filter'
    match '/*path', to: 'proxy_rules#filter'
  end

  def sub_domain?(request)
    Domain.new(request).subdomain_request?
  end
end

app/models/proxy_rule.rb
class ProxyRule < ActiveRecord::Base
  VALID_DOMAIN_REGEX = /\A(?:[A-Za-z0-9][A-Za-z0-9\-]{0,61}[A-Za-z0-9]|[A-Za-z0-9])\z/
  TARGET_IPADDR_RANGE = '2001:200:0:889c::/64'

  belongs_to :user

  validates :name, presence: true
  validates :domain, format: { with: VALID_DOMAIN_REGEX }, uniqueness: true
  validates :url, format: { with: /\Ahttps?:/ }
  validate do
    next if self.user.super_user?

    require 'addressable/uri'
    begin
      target_addr = IPAddr.new(Addressable::URI.parse(self.url).hostname)
      unless IPAddr.new(TARGET_IPADDR_RANGE).include?(target_addr)
        errors.add(:url, :has_invalid_target)
      end
    rescue
      errors.add(:url, :has_parse_error)
    end
  end
  enum auth_type: { open: 0, intranet: 1, slack_auth: 2 }

  scope :active, -> { where('expired_at IS NULL OR expired_at > ?', Time.now) }

  def link_url
    "#{self.https? ? 'https' : 'http'}://#{self.domain}.#{Domain::BASE_DOMAIN}"
  end
end

app/models/slack_credential.rb
class SlackCredential < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :slack_credential
  has_many :proxy_rules

  enum role: { normal_user: 0, manage_user: 1, super_user: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def domain
    @domain ||= Domain.new(request)
  end
  helper_method :domain

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/proxy_rules_controller.rb
class ProxyRulesController < ApplicationController
  include ReverseProxy::Controller

  before_action :require_current_user, except: :filter
  before_action :set_proxy_rule, only: [:show, :edit, :update, :destroy]

  WIDE_IPADDR_RANGE = '203.178.0.0/16'

  def index
    @proxy_rules = ProxyRule.active
  end

  def new
    @proxy_rule = ProxyRule.new
  end

  def create
    @proxy_rule = ProxyRule.new(proxy_rule_params.merge(user: current_user))
    if @proxy_rule.save
      redirect_to proxy_rules_path, notice: 'ルールを登録しました'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @proxy_rule.update(proxy_rule_params)
      redirect_to proxy_rules_path, notice: 'ルールを編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    if @proxy_rule.update(expired_at: Time.now)
      redirect_to proxy_rules_path, notice: 'ルールを削除しました'
    else
      render 'edit'
    end
  end

  def filter
    @proxy_rule = ProxyRule.active.find_by(domain: domain.subdomain)
    if @proxy_rule.blank?
      redirect_to domain.original_url(proxy_rules_path)
      return
    end

    if @proxy_rule.intranet? && !request_from_wide?
      redirect_to domain.original_url(root_path)
      return
    end

    if @proxy_rule.slack_auth? && current_user.blank?
      redirect_to domain.original_url(auth_path(:slack, state: domain.subdomain))
      return
    end

    if @proxy_rule.https? != request.ssl?
      redirect_to @proxy_rule.link_url + request.path
      return
    end

    require 'addressable/template'
    reverse_proxy @proxy_rule.url
  end

  private

  def require_current_user
    redirect_to domain.original_url(auth_path(:slack)) if current_user.blank?
  end

  def set_proxy_rule
    @proxy_rule = ProxyRule.active.find_by(id: params[:id])

    if @proxy_rule.blank?
      redirect_to status: :not_found
      return
    end

    if @proxy_rule.user != current_user && current_user.normal_user?
      redirect_to status: :forbidden
      return
    end
  end

  def proxy_rule_params
    params.require(:proxy_rule).permit(:name, :domain, :url, :auth_type, :https, :expired_at)
  end

  def request_from_wide?
    IPAddr.new(WIDE_IPADDR_RANGE).include?(IPAddr.new(request.ip))
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def slack_callback
    auth = request.env['omniauth.auth']

    credential = SlackCredential.find_or_initialize_by(slack_user_id: auth.info.user_id)
    user = if credential.new_record?
      User.create(email: auth.info.email,
                  name: auth.info.name,
                  nickname: auth.info.nickname,
                  icon_url: auth.extra.user_info.user.profile.image_192,
                  slack_credential: credential)
    else
      credential.user
    end

    session[:user_id] = user.id

    state = request.env['omniauth.params']['state']
    if state
      proxy_rule = ProxyRule.active.find_by(domain: state)
      redirect_to proxy_rule.link_url
    else
      redirect_to root_path
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    if content_for?(:title)
      content_for(:title)
    else
      'Arch Http Gateway'
    end
  end
end

app/helpers/proxy_rules_helper.rb
module ProxyRulesHelper
  def editable_rule?(rule)
    rule.user == current_user || !current_user.normal_user?
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= title
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse
      .container
        .navbar-header
          = link_to title, root_path, class: 'navbar-brand'
        #navbar.navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li{ class: current_page?(root_path) ? 'active' : '' }
              = link_to 'Home', root_path
            %li{ class: current_page?(proxy_rules_path) ? 'active' : '' }
              = link_to 'ルール一覧', proxy_rules_path
            %li{ class: current_page?(new_proxy_rule_path) ? 'active' : '' }
              = link_to 'ルールを作成', new_proxy_rule_path
          %ul.nav.navbar-nav.navbar-right
            - if current_user.blank?
              %li
                = link_to 'ログインする', auth_path(:slack)
            - else
              %li
                %a= current_user.name

    - if flash[:notice]
      .container
        %p.bg-success= flash[:notice]

    = yield

app/views/proxy_rules/_form.html.haml
.container
  - @proxy_rule.errors.full_messages.each do |error|
    %p.bg-danger= error

  = form_for @proxy_rule do |f|
    .form-group
      %label Name
      = f.text_field :name, class: 'form-control', placeholder: '内部WIKI'
    .form-group
      %label Domain
      = f.text_field :domain, class: 'form-control', placeholder: 'wiki'
    .form-group
      %label Url
      = f.text_field :url, class: 'form-control', placeholder: 'http://203.178.128.99/'
    .form-group
      %label Auth Type
      = f.select :auth_type, ProxyRule.auth_types.keys, {}, class: 'form-control'
    .form-group
      %label Force HTTPS
      = f.check_box :https
    = f.submit

app/views/proxy_rules/edit.html.haml
= render 'form'

app/views/proxy_rules/index.html.haml
.container
  %table.table.table-striped
    %thead
      %tr
        %th #
        %th User
        %th Name
        %th Domain
        %th Url
        %th Auth Type
        %th HTTPS
        %th Action
    %tbody
      - @proxy_rules.each do |rule|
        %tr
          %td= rule.id
          %td= rule.user.name
          %td= rule.name
          %td= link_to rule.domain, rule.link_url
          %td= rule.url
          %td= rule.auth_type
          %td= rule.https
          %td
            - if editable_rule?(rule)
              = link_to fa_icon('pencil'), edit_proxy_rule_path(rule)
              = link_to fa_icon('trash-o'), proxy_rule_path(rule), method: :delete

app/views/proxy_rules/new.html.haml
= render 'form'